# Generated by Django 3.0.3 on 2020-07-11 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Erros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('decricao', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(default=datetime.datetime.now)),
                ('eventos', models.CharField(max_length=50)),
            ],
        ),
    ]
