# Generated by Django 3.0.3 on 2020-07-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='erros',
            old_name='decricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='erros',
            old_name='data_hora',
            new_name='origem',
        ),
    ]
