# Generated by Django 3.0.3 on 2020-07-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erros', '0003_auto_20200714_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erros',
            name='categoria',
            field=models.CharField(choices=[('1', 'Produção'), ('2', 'Homologação'), ('3', 'Desenvolvimento'), ('4', 'Arquivado')], max_length=1, verbose_name='Categoria'),
        ),
    ]
