# Generated by Django 3.0.3 on 2020-07-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erros', '0006_auto_20200715_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erros',
            name='categoria',
            field=models.CharField(choices=[('1', 'Produção'), ('2', 'Homologação'), ('3', 'Desenvolvimento')], max_length=50, verbose_name='Categoria'),
        ),
    ]
