# Generated by Django 3.0.3 on 2020-07-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erros', '0009_auto_20200715_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erros',
            name='categoria',
            field=models.CharField(choices=[('Producao', 'Produção'), ('Homologacao', 'Homologação'), ('Desenvolvimento', 'Desenvolvimento')], max_length=50, verbose_name='Categoria'),
        ),
    ]
