# Generated by Django 3.1.3 on 2020-11-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erros', '0010_auto_20200715_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erros',
            name='categoria',
            field=models.CharField(choices=[('Produção', 'Produção'), ('Homologação', 'Homologação'), ('Desenvolvimento', 'Desenvolvimento')], max_length=50, verbose_name='Categoria'),
        ),
    ]
